// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 32-bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Tue Nov 13 13:05:05 2018

all_uart all_uart_inst
(
	.res(res_sig) ,	// input  res_sig
	.RX(RX_sig) ,	// input  RX_sig
	.clk(clk_sig) ,	// input  clk_sig
	.TX(TX_sig) ,	// output  TX_sig
	.CLK_50(CLK_50_sig) ,	// output  CLK_50_sig
	.CLC_10(CLC_10_sig) 	// output  CLC_10_sig
);

